# [build]
#   node_bundler = "esbuild"
#   # command = "npm run build"
#   functions = "functions/"
#   # publish = "public/"
  

[build]
  command = "npm run build"

  functions = "functions/"

  publish = "public/"
  
# [functions]
#         node_bundler = "esbuild"